[build]
  base = "FClub.WebAdmin/"
  publish = "build/"
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404